"""
Django settings for yellowant_BOX project.

Generated by 'django-admin startproject' using Django 1.11.13.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
data = open('yellowant_app_credentials.json').read()
data_json = json.loads(data)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

app_name = os.environ.get("HEROKU_APP_NAME")
BASE_URL = "https://{}.herokuapp.com".format(app_name)
ALLOWED_HOSTS = ['*', '{}.herokuapp.com'.format(app_name)]


### YellowAnt specific settings ###
# URL to obtain oauth2 access for a YA user
YA_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
# URL to receive oauth2 codes from YA for user authentication. As a developer, you need to provide this URL in the YA
# developer console so that YA knows exactly where to send the oauth2 codes.
YA_REDIRECT_URL =BASE_URL + "redirecturl/" #"https://00c6567b.ngrok.io/redirecturl/"

# Numerical ID generated when you register your application through the YA developer console
BASE_HREF="/"
SITE_PROTOCOL = "https://"


YA_APP_ID = str(data_json['application_id'])
# Client ID generated from the YA developer console. Required to identify requests from this application to YA
YA_CLIENT_ID = str(data_json['client_id'])
# Client secret generated from the YA developer console. Required to identify requests from this application to YA
YA_CLIENT_SECRET = str(data_json['client_secret'])
# Verification token generated from the YA developer console. This application can verify requests from YA as they will
# carry the verification token
YA_VERIFICATION_TOKEN = str(data_json['verification_token'])

### END YellowAnt specific settings ###

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k=vl955hht@2=reb1-y#=ieldbhd4-n39)1ue18rzq17$)4k*v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


DEV_ENV = os.environ.get('ENV', 'DEV')
if DEV_ENV == "DEV":
    CLIENT_ID = "4qerinz9kgy7adw653wb90co0vg1drt8"
    CLIENT_SECRET = "z0tvo8H3OqJR18Vga6zp9Ua1jYdAPF62"
    BASE_URL = "https://dd272eb3.ngrok.io"
    SITE_DOMAIN_URL = "ngrok.io"
elif DEV_ENV == "HEROKU":
    CLIENT_ID = os.environ.get("BOX_CLIENT_ID", "")
    CLIENT_SECRET = os.environ.get("BOX_CLIENT_SECRET", "")
    BASE_URL = "https://{}.herokuapp.com/".format(app_name)
    app_name = os.environ.get("HEROKU_APP_NAME")
    SITE_DOMAIN_URL = "herokuapp.com"

#Specific to BOX----------



#Specific to BOX-----------

# Application definition

INSTALLED_APPS = [
    'lib.yellowant_api',
    'lib.web',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yellowant_BOX.urls'
CORS_ORIGIN_ALLOW_ALL = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yellowant_BOX.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'box_db',
        'USER':'root',
        'PASSWORD':'abhiawesome007',
        'PORT':'',
    }
}



if DEV_ENV == "HEROKU":
    import dj_database_url
    db_from_env = dj_database_url.config()
    DATABASES['default'].update(db_from_env)
    DATABASES['default']['CONN_MAX_AGE'] = 500
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')